server:
  port: 8084
  servlet:
    context-path: /wos
spring:
  application:
    name: wos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wos?Unicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  thymeleaf:
    mode: HTML5
  freemarker:
    request-context-attribute: req
    suffix: .ftl
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
mybatis:
  mapper-locations: classpath:/mappers/*/*Mapper.xml
  config-location: classpath:/conf/mybatis-conf.xml